name: cpp-cmake-prebuilt-release-actions-workflow

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    strategy:
      matrix:
        container: [ ubuntu-latest, macos-latest, windows-latest ]
        build_type: [ Release ]


    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Ubuntu
        if: ${{ matrix.container == 'ubuntu-latest' }}
        shell: bash
        # Configure CMake in a 'buildX' subdirectory.
        # We can't use `build` as `BUILD` is already taken by the bazel build file.
        # On Mac and Windows this leads to a conflict.
        run: |
          cmake -DCMAKE_EXE_LINKER_FLAGS="-static" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -B./cmake-build
            
      - name: Configure
        if: ${{ matrix.container == 'macos-latest' }}
        shell: bash
        # Configure CMake in a 'buildX' subdirectory.
        # We can't use `build` as `BUILD` is already taken by the bazel build file.
        # On Mac and Windows this leads to a conflict.
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -B./cmake-build
            
      - name: Configure
        if: ${{ matrix.container == 'windows-latest' }}
        shell: bash
        # Configure CMake in a 'buildX' subdirectory.
        # We can't use `build` as `BUILD` is already taken by the bazel build file.
        # On Mac and Windows this leads to a conflict.
        run: |
          cmake -DCMAKE_EXE_LINKER_FLAGS="-static" -G"MinGW Makefiles" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -B./cmake-build

      - name: cmake Build
        run: |
          cd cmake-build
          cmake --build . --config ${{ matrix.build_type }}
          
      - if: ${{ matrix.container == 'windows-latest' }} 
        shell: cmd
        run: |
          cd cmake-build &&^
          echo println("hahahah"); > main.hahahaha &&^
          .\pe-builder.exe
          
      - if: ${{ matrix.container != 'windows-latest' }} 
        run: |
          cd cmake-build && \
          echo 'println("hahahah");' > main.hahahaha && \
          ./pe-builder
          
      - if: ${{ matrix.container == 'macos-latest' }}
        name: Archive Release for macOS
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            pe-builder
            main.exe
          directory: "cmake-build"
          filename: pe-builder-${{ github.ref_name }}-macos-clang-14.0.0.14000029.zip
          
      - if: ${{ matrix.container == 'windows-latest' }}
        name: Archive Release for Windows
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            pe-builder.exe
            main.exe
          directory: "cmake-build"
          filename: pe-builder-${{ github.ref_name }}-mingw64-x86_64-posix-seh-11.2.0.zip
          
      - if: ${{ matrix.container == 'ubuntu-latest' }}
        name: Archive Release for Ubuntu
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            pe-builder
            main.exe
          directory: "cmake-build"
          filename: pe-builder-${{ github.ref_name }}-ubuntu-gcc-11.3.0.zip
          
      - if: ${{ matrix.container == 'windows-latest' }}
        name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: cmake-build/pe-builder-v1.0.0-mingw64-x86_64-posix-seh-11.2.0.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - if: ${{ matrix.container == 'macos-latest' }}
        name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: cmake-build/pe-builder-v1.0.0-macos-clang-14.0.0.14000029.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - if: ${{ matrix.container == 'ubuntu-latest' }}
        name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: cmake-build/pe-builder-v1.0.0-ubuntu-gcc-11.3.0.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
